# Github Action workflow that is run on push and runs bin/updateindex.sh and if that changes anything, commits and pushes the changes.
name: Update Index

on:
  push:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run updateindex script
      run: |
        chmod +x bin/updateindex.sh
        ./bin/updateindex.sh

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Action Update Index'
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update index via GitHub Action"
        git push
