# Github Action workflow that is run on push and runs bin/updateindex.sh and if that changes anything, commits and pushes the changes.
name: Update Index
run-name: Update Index from ${{ github.ref_name }}

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action Update Index'
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout master
          # merge in develop with strategy theirs
          git merge develop --no-ff -X theirs

      - name: List files
        run: |
          find . -type f

      - name: Run updateindex script
        run: |
          chmod +x bin/updateindex.sh
          ./bin/updateindex.sh

      - name: Recreate sitemap
        run: |
          chmod +x bin/generate_sitemap.sh
          ./bin/generate_sitemap.sh

      - name: Update file change times
        run: |
          chmod +x bin/updatetimes.sh
          ./bin/updatetimes.sh

      - name: Commit and push changes
        run: |
          git add -A
          git commit --amend --no-edit -m "[Github Actions] Update Index, times, sitemap"
          git push origin master
